# Generated by Django 5.0.1 on 2024-04-25 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioNormal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('administracion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.usuarioadminstracion')),
            ],
            options={
                'verbose_name': 'Usuario (cliente)',
                'verbose_name_plural': 'Usuarios (clientes)',
            },
        ),
    ]
