# Generated by Django 5.0.1 on 2024-04-25 18:11

import apps.Global.models
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('paypalMail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='paypalMail')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI')),
                ('calle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Calle')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('cPostal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Postal')),
                ('provincia', models.CharField(blank=True, choices=[('AL', 'Almería'), ('CA', 'Cádiz'), ('CO', 'Córdoba'), ('GR', 'Granada'), ('HU', 'Huelva'), ('JA', 'Jaén'), ('MA', 'Málaga'), ('SE', 'Sevilla'), ('AB', 'Albacete'), ('CR', 'Ciudad Real'), ('CU', 'Cuenca'), ('GU', 'Guadalajara'), ('TO', 'Toledo'), ('AV', 'Ávila'), ('BU', 'Burgos'), ('LE', 'León'), ('P', 'Palencia'), ('SA', 'Salamanca'), ('SG', 'Segovia'), ('SO', 'Soria'), ('VA', 'Valladolid'), ('ZA', 'Zamora'), ('HU', 'Huesca'), ('TE', 'Teruel'), ('Z', 'Zaragoza'), ('O', 'Asturias'), ('C', 'Cantabria'), ('VI', 'Álava'), ('BI', 'Bizkaia'), ('SS', 'Gipuzkoa'), ('C', 'A Coruña'), ('LU', 'Lugo'), ('OU', 'Ourense'), ('PO', 'Pontevedra'), ('BA', 'Badajoz'), ('CC', 'Cáceres'), ('TF', 'Santa Cruz de Tenerife'), ('GC', 'Las Palmas'), ('CE', 'Ceuta'), ('ML', 'Melilla'), ('MU', 'Murcia'), ('MD', 'Madrid'), ('LO', 'La Rioja'), ('H', 'Huesca'), ('AS', 'Asturias'), ('S', 'Cantabria'), ('ZA', 'Zaragoza'), ('NA', 'Navarra'), ('PV', 'País Vasco')], max_length=10, null=True, verbose_name='Provincia')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_administracion', models.BooleanField(default=False)),
                ('starter', models.BooleanField(default=False)),
                ('is_nomalUser', models.BooleanField(default=False)),
                ('telefono', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telefono (+34)')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/%Y/%m/%d')),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('juego', models.CharField(choices=[('Loteria Nacional Sábado', 'Lotería Nacional Sábado'), ('Loteria Nacional Jueves', 'Lotería Nacional Jueves'), ('Loteria Nacional', 'Lotería Nacional'), ('Loteria Niño', 'Loteria Niño'), ('Loteria Navidad', 'Loteria Navidad'), ('Quinigol', 'Quinigol'), ('Quiniela', 'Quiniela'), ('Bonoloto', 'Bonoloto'), ('Euromillón', 'Euromillón'), ('Eurodreams', 'Eurodreams'), ('Primitiva', 'Primitiva'), ('El Gordo', 'El Gordo')], max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/%Y/%m/%d')),
                ('fecha_sorteo', models.DateField(blank=True, null=True, verbose_name='Fecha del Sorteo')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('codigovalidez', models.CharField(blank=True, max_length=200)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Global.category')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdminstracion',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_administracion', models.CharField(max_length=400, unique=True, verbose_name='Administracion')),
                ('cif', models.CharField(max_length=9, unique=True, verbose_name='CIF')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.pack')),
            ],
            options={
                'verbose_name': 'Administración',
                'verbose_name_plural': 'Administraciones',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryAdministration',
            fields=[
                ('nombreAdministración', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Global.usuarioadminstracion')),
                ('logo', models.ImageField(blank=True, default='LotoFinder/static/imgs/logo.png', upload_to=apps.Global.models.user_directory_path)),
                ('imagen_cabecera', models.ImageField(blank=True, null=True, upload_to=apps.Global.models.user_directory_path)),
                ('color_primario', models.CharField(default='#ffffff', max_length=7)),
                ('color_footer', models.CharField(default='#000000', max_length=7)),
                ('color_secundario', models.CharField(default='#000000', max_length=7)),
                ('color_body', models.CharField(default='#fffff', max_length=7)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_apertura', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('otros_servicios', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('promociones', models.TextField(blank=True, null=True)),
                ('productos_destacados', models.TextField(blank=True, null=True)),
                ('testimonios', models.TextField(blank=True, null=True)),
                ('politicas_devolucion', models.TextField(blank=True, null=True)),
                ('puntos_de_venta', models.TextField(blank=True, null=True)),
                ('eventos_especiales', models.TextField(blank=True, null=True)),
                ('partners', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('idioma_preferido', models.CharField(blank=True, max_length=50, null=True)),
                ('moneda_preferida', models.CharField(blank=True, max_length=50, null=True)),
                ('politicas_privacidad_resumen_title', models.TextField(blank=True, null=True)),
                ('politicas_privacidad_title', models.TextField(blank=True, null=True)),
                ('politicas_cookies_title', models.TextField(blank=True, null=True)),
                ('politicas_privacidad_resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('politicas_privacidad', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('politicas_cookies', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.Global.models.user_directory_path)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombreAdministración', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='Global.usuarioadminstracion')),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icono', models.CharField(max_length=100)),
                ('nombreAdministración', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redsocial', to='Global.usuarioadminstracion')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='administracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Global.usuarioadminstracion'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypalId', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completado', models.BooleanField(default=False)),
                ('correoCliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('calle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Calle')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('cPostal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Postal')),
                ('provincia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Provincia')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('validado', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.pack')),
                ('productos', models.ManyToManyField(blank=True, to='Global.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Global.usuarioadminstracion')),
            ],
        ),
        migrations.CreateModel(
            name='contactoUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('asunto', models.TextField(blank=True, max_length=200, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('nombreAdministración', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactUs', to='Global.usuarioadminstracion')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
